import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4-turbo")
QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY", None)
QDRANT_COLLECTION = os.getenv("QDRANT_COLLECTION", "book_content")
MAX_RESPONSE_TOKENS = int(os.getenv("MAX_RESPONSE_TOKENS", "1000"))
REQUEST_TIMEOUT = int(os.getenv("REQUEST_TIMEOUT", "30"))

settings = type('Settings', (object,), {
    'OPENAI_API_KEY': OPENAI_API_KEY,
    'OPENAI_MODEL': OPENAI_MODEL,
    'QDRANT_URL': QDRANT_URL,
    'QDRANT_API_KEY': QDRANT_API_KEY,
    'QDRANT_COLLECTION': QDRANT_COLLECTION,
    'MAX_RESPONSE_TOKENS': MAX_RESPONSE_TOKENS,
    'REQUEST_TIMEOUT': REQUEST_TIMEOUT
})
