"""
Plan data model for the Physical AI & Humanoid Robotics project.

This module defines the Plan entity with all required attributes as
specified in the data model.
"""
from typing import List, Optional
from uuid import uuid4, UUID
from datetime import datetime
from enum import Enum

class PlanStatus(Enum):
    PENDING = "pending"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"

class Action:
    """Individual action within a plan that the robot should execute."""
    
    def __init__(
        self,
        type_: str,
        parameters: dict,
        id_: Optional[UUID] = None,
        status: str = "pending",
        execution_order: int = 0
    ):
        self.id = id_ or uuid4()
        self.type = type_
        self.parameters = parameters
        self.status = status
        self.execution_order = execution_order

class Plan:
    """Structured sequence of actions generated by the AI planning layer that the robot will execute."""
    
    def __init__(
        self,
        command_id: UUID,
        actions: List[Action],
        id_: Optional[UUID] = None,
        status: PlanStatus = PlanStatus.PENDING,
        created_at: Optional[datetime] = None,
        completed_at: Optional[datetime] = None
    ):
        if len(actions) == 0:
            raise ValueError("Plan must contain at least one Action")
        
        self.id = id_ or uuid4()
        self.command_id = command_id
        self.actions = actions
        self.status = status
        self.created_at = created_at or datetime.now()
        self.completed_at = completed_at
    
    def to_dict(self):
        """Convert the plan to a dictionary representation."""
        return {
            "id": str(self.id),
            "command_id": str(self.command_id),
            "status": self.status.value,
            "actions": [
                {
                    "id": str(action.id),
                    "type": action.type,
                    "parameters": action.parameters,
                    "status": action.status,
                    "execution_order": action.execution_order
                }
                for action in self.actions
            ],
            "created_at": self.created_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None
        }
    
    @classmethod
    def from_dict(cls, data: dict):
        """Create a Plan instance from a dictionary."""
        actions = [
            Action(
                id_=UUID(action_data["id"]),
                type_=action_data["type"],
                parameters=action_data["parameters"],
                status=action_data["status"],
                execution_order=action_data["execution_order"]
            )
            for action_data in data["actions"]
        ]
        
        return cls(
            id_=UUID(data["id"]),
            command_id=UUID(data["command_id"]),
            actions=actions,
            status=PlanStatus(data["status"]),
            created_at=datetime.fromisoformat(data["created_at"]),
            completed_at=datetime.fromisoformat(data["completed_at"]) if data["completed_at"] else None
        )